version: '3.4'

services:
  bsetracker.web:
    image: repo.treescale.com/bsetracker/bsetracker
    container_name: web
    build:
      context: .
      dockerfile: src/BSETracker.Web/Dockerfile
    depends_on: 
      - postgres
      - redis

  bsetracker.cron:
    image: repo.treescale.com/bsetracker/cron
    container_name: timer
    build:
      context: ./cron
      dockerfile: Dockerfile
    depends_on:
      - bsetracker.web

  postgres:
    container_name: db
    image: postgres:10-alpine

  redis:
    container_name: cache
    image: redis:4-alpine3.8
