version: '3.4'

services:
  bsetracker.web:
    image: repo.treescale.com/bsetracker/bsetracker
    container_name: web
    build:
      context: ./src/services/BSETracker.Web
      dockerfile: Dockerfile
    depends_on: 
      - postgres
      - redis

  bsetracker.cron:
    image: repo.treescale.com/bsetracker/cron
    container_name: timer
    build:
      context: ./src/services/cron
      dockerfile: Dockerfile
    depends_on:
      - bsetracker.web

  postgres:
    container_name: db
    image: postgres:10-alpine

  redis:
    container_name: cache
    image: redis:4-alpine3.8

  nginx:
    container_name: nginx
    image: repo.treescale.com/bsetracker/nginx
    build:
      context: ./src/services/nginx
      dockerfile: Dockerfile
    depends_on: 
      - bsetracker.web
