version: '3.4'

services:
  bsetracker.web:
    image: repo.treescale.com/bsetracker/bsetracker
    build:
      context: .
      dockerfile: src/BSETracker.Web/Dockerfile
    depends_on: 
      - postgres

  postgres:
    image: postgres:10-alpine
