version: '3.4'

services:
  bsetracker.web:
    image: repo.treescale.com/bsetracker/bsetracker
    container_name: web
    build:
      context: .
      dockerfile: src/BSETracker.Web/Dockerfile
    depends_on: 
      - postgres

  bsetracker.cron:
    image: repo.treescale.com/bsetracker/cron
    container_name: cron
    build:
      context: ./cron
      dockerfile: Dockerfile
    depends_on:
      - bsetracker.web

  postgres:
    container_name: db
    image: postgres:10-alpine
